config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'saunas/index'
  root to: "saunas#index"
  resources :saunas
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sauna.rb
class Sauna < ApplicationRecord
  belongs_to :user
  
  validates :shop,      presence: true
  validates :hot,       presence: true
  validates :ice,       presence: true
  validates :chill,     presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :saunas

  validates :nickname,     presence: true
  validates :password,                    format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze, message: "is invalid. Input full-width katakana characters."}
  validates :lastname,     presence: true,format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "is invalid. Input full-width characters."} 
  validates :sub_lastname, presence: true,format: {with: /\A[ァ-ヶー]+\z/,} 
  validates :name,         presence: true,format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "is invalid. Input full-width characters."} 
  validates :sub_name,     presence: true,format: {with: /\A[ァ-ヶー]+\z/,           message: "is invalid. Input full-width katakana characters."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :lastname, :sub_lastname, :name, :sub_name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/saunas_controller.rb
class SaunasController < ApplicationController
  before_action :set_sauna, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user!, except:[:index]
  before_action :move_to_index, only: [:edit,:update,:destroy]
  def index
    @saunas = Sauna.all
  end

  def new
    @sauna = Sauna.new
  end
  
  def create
    @sauna = Sauna.new(sauna_params)
   if @sauna.save
    redirect_to root_path
   else
    render :new
   end
  end

  def show
  end

  def edit
  end

  def update
    @sauna.update(sauna_params)
    redirect_to root_path
  end
 
  def destroy
    @sauna.destroy
    redirect_to root_path
  end

  private

  def sauna_params
    params.require(:sauna).permit(:shop, :hot, :ice, :chill).merge(user_id: current_user.id)
  end

  def set_sauna
    @sauna = Sauna.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user == @sauna.user 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @saunas = Sauna.all
    @saunas = @user.saunas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaunaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
   <div class="sauna">
   <header class="header">
      <div class="header-left">
        <h1 class="title"><%=link_to "sauna.life", root_path %></h1>
      </div>
      <ul class="center-lists">
        <li><%= link_to "サ活投稿" ,new_sauna_path ,class:"post" %></li>
        <li><%= link_to "サウナ辞書", class:"post"%></li>
      </ul>
      <ul class="right-lists">
        <% if user_signed_in? %>
          <li><%= link_to "マイページ" ,user_path(current_user) ,class:"post"%></li>
          <li><%= link_to "ログアウト" ,destroy_user_session_path, method: :delete ,class:"post"%></li> 
          <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path, class:"post" %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class:"post" %></li>
        <% end %>
      </ul>
   </header>
   </div>
  <div id="key_visual">
  <div class="slider">
    <div>
        <%= image_tag "iStock-1163221036.jpg"%>
    </div>
    <div>
        <%= image_tag "sauna_house.jpg"%>
    </div>
    <div>
        <%= image_tag "water_pool.jpg"%>
    </div>
  </div>
  </div>
    <%= yield %>

    <footer>
      <p>
        Copyright Sauna.life 2022.
      </p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script>
     $(document).ready(function(){
    $(".slider").slick({
     arrows: false,
     dots: true,
     autoplay: true
     });
    });
    </script>
  </body>
</html>

app/views/saunas/_form.html.erb
<%= form_with model:@sauna, local: true do |form| %>
    <div class="sauna-content">
      <div class="sauna-shop-name">店名</div>
        <%= form.text_field :shop,class:'shop-form' ,placeholder: "  text", rows: "10" %>
      <div class="sauna-title">サウナ</div>
        <%= form.text_area :hot,class:'sauna-form' ,placeholder: "  text", rows: "10" %>
      <div class="sauna-title">水風呂</div>
        <%= form.text_area :ice,class:'sauna-form', placeholder: "  text", rows: "10" %>
      <div class="sauna-title">外気浴</div>
        <%= form.text_area :chill,class:'sauna-form', placeholder: "  text", rows: "10" %>
    </div>

      <div class="sauna-btn">
        <%= form.submit "投稿する" ,class:"sauna-btn" %>
        <%= link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    <% end %>

app/views/saunas/_sauna.html.erb
<div class="only-sauna">
  <div class="sauna-article">
    <div class="article-name">
      <%= link_to sauna.user.nickname ,user_path(sauna.user.id)%>
    <div class="sauna-text">店名</div>
      <div class="sauna-shop">
        <p><%= sauna.shop%></p>
      </div>
    <div class="sauna-text">サウナ</div>
      <div class="sauna-message">
        <p><%= sauna.hot%></p>
      </div>
    <div class="sauna-text">水風呂</div>
      <div class="sauna-message">
         <p><%= sauna.ice%></p>
      </div>
    <div class="sauna-text">外気浴</div>
      <div class="sauna-message">
        <p><%= sauna.chill%></p>
      </div>
  </div>
</div>
</div>

app/views/saunas/edit.html.erb
<div class="edit-sauna">
  <div class="sauna-content">
    <div class="sauna-text">
    <h3 class="edit-contet">編集する</h3>
      <%= render partial: "form", locals: {sauna: @sauna} %>
    </div>
  </div> 
</div>

app/views/saunas/index.html.erb
   <% @saunas.each do |sauna| %>
    <%= render partial: "sauna", locals: {sauna: sauna} %> 
   <% end %>
  

app/views/saunas/new.html.erb
<div class="contents">
  <div class ="container">
  <div class="new-header-text">
    <h1 class="form-title"><%=link_to "サ活　投稿", root_path%></h1>
  </div>
   <%= render partial: "form", locals: { sauna: @sauna } %>
  </div>
</div>

    

app/views/saunas/show.html.erb
  <div class="only-sauna">
  <div class="sauna-article">
   <div class="article-name">
      <%= link_to @sauna.user.nickname ,user_path(@sauna.user.id),class:"article-post-name"%>
    <div class="sauna-text">店名</div>
      <div class="sauna-shop">
        <p><%= @sauna.shop%></p>
      </div>
    <div class="sauna-text">サウナ</div>
      <div class="sauna-message">
        <p><%= @sauna.hot%></p>
      </div>
    <div class="sauna-text">水風呂</div>
      <div class="sauna-message">
         <p><%= @sauna.ice%></p>
      </div>
    <div class="sauna-text">外気浴</div>
      <div class="sauna-message">
        <p><%= @sauna.chill%></p>
      </div>
  <% if user_signed_in? && current_user.id == @sauna.user_id %>
  <div class="saunas-lists">
    <ul class="sauna-list">
      <li>
        <%= link_to '編集', edit_sauna_path(@sauna.id)%>
      </li>
      <li>
        <%=link_to '削除',sauna_path(@sauna), method: :delete %>
      </li>
    </ul>
  </div>
  <%end%>
  </div>
  </div>
  </div>
  
 

app/views/users/show.html.erb
<div class="my-page">
  <div class="my-name">
    <%= "#{@user.nickname}  サ活一覧"%>
  </div>
<% if user_signed_in?%>
  <div class="my-sauna">
    <% @saunas.each do |sauna| %>
      <ul>
        <li class="my-sauna-shop"><%=link_to sauna.shop , sauna_path(sauna.id)%></li>
      </ul>
    <%end%>
<%else%>
      <ul>
        <li ><%=link_to @sauna.shop , sauna_path(sauna.id)%></li>
      </ul>
  </div>
<%end%>